// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getSupabasePublishableKey, getSupabaseUrl } from './env'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    if (!getSupabaseUrl() || !getSupabasePublishableKey()) {
      return next({ headers: {} })
    }
    // Force a refresh if the access token is expired so custom-domain
    // sessions still send a usable JWT to server functions.
    await supabase.auth.getUser().catch(() => undefined)
    const { data } = await supabase.auth.getSession()
    const token = data.session?.access_token
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
